swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "0.5.0"
  title: Swagger REST API for O3as
consumes:
  - "application/json"

basePath: "/api"

parameters:
  ModelParam:
    in: query
    name: model
    type: array
    items:
      type: string
    description: Name(s) of model(s) (dataset-model)
    default: [CCMI-1_ACCESS_ACCESS-CCM-refC2,CCMI-1_CCCma_CMAM-refC2,CCMI-1_CHASER-MIROC-ESM-refC2]
    required: true
  YearBeginParam:
    name: begin
    in: query
    type: integer
    description: Year to start data scanning from
    default: 1959
    required: false
  YearEndParam:
    name: end
    in: query
    type: integer
    description: Year to finish data scanning
    default: 2100
    required: false
  MonthParam:
    name: month
    in: query
    type: array
    items:
      type: integer
    description: Month(s) to select, if not a whole year
    default: []
    required: false
  LatMinParam:
    name: lat_min
    in: query
    type: integer
    description: Latitude (min) to define the range (-90..90)
    default: -90
    required: false
  LatMaxParam:
    name: lat_max
    in: query
    type: integer
    description: Latitude (max) to define the range (-90..90)
    default: 90
    required: false  

# Paths supported by the server application
paths:
  /api-info:
    get:
      operationId: "o3api.api.get_api_info"
      tags:
        - "api-info"
      summary: "Returning information about the service"
      description: "Return o3api metadata"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successfully returned o3api info"
          schema:
            $ref: '#/definitions/MetaInfo'
  /data:
    get:
      operationId: "o3api.api.get_data_types"
      tags:
        - "data"
      summary: "Returning list of plot types with available data"
      description: "Return list of plot types with available data"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successfully returned list of data types"
          schema:
            $ref: '#/definitions/ListData'
  /data/tco3_zm:
    post:
      operationId: "o3api.api.get_data_tco3_zm"
      tags:
        - "data"
      summary: "Get raw data for tco3_zm"
      description: "Get raw data for tco3_zm"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/ModelParam'
        - $ref: '#/parameters/YearBeginParam'
        - $ref: '#/parameters/YearEndParam'
        - $ref: '#/parameters/MonthParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
      responses:
        200:
          description: "Successfully retrieved the data"
          schema:
            type: file
          schema:
            $ref: '#/definitions/TCO3Data'
#        default:
#          description: "Unexpected error"
#          schema:
#            $ref: "#/definitions/Error"
### comment /data/tco3_return for now, until we decide on params # vkoz@210424
#  /data/tco3_return:
#    post:
#      operationId: "o3api.api.get_data_tco3_return"
#      tags:
#        - "data"
#      summary: "Get raw data for tco3_return"
#      description: "Get raw data for tco3_return"
#      produces:
#        - "application/json"
#      parameters:
#        - $ref: '#/parameters/ModelParam'
#        - $ref: '#/parameters/YearBeginParam'
#        - $ref: '#/parameters/YearEndParam'
#        - $ref: '#/parameters/MonthParam'
#        - $ref: '#/parameters/LatMinParam'
#        - $ref: '#/parameters/LatMaxParam'
#      responses:
#        200:
#          description: "Successfully retrieved the data"
#          schema:
#            type: file
#          schema:
#            $ref: '#/definitions/TCO3ReturnData'
##        default:
##          description: "Unexpected error"
##          schema:
##            $ref: "#/definitions/Error"
###
  /models:
    get:
      operationId: "o3api.api.get_models_info"
      tags:
        - "models"
      summary: "Returning list of available models + short info"
      description: "Return list of models + short info"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successfully returned list of models + short info"
          schema:
            $ref: '#/definitions/Models'
  /models/list/{ptype}:
    post:
      operationId: "o3api.api.list_models"
      tags:
        - "models"
      summary: "Returning list of models for a certain plot type"
      description: "Return list of models for a certain plot type"
      produces:
        - "application/json"
      parameters:
        - name: ptype
          in: path
          type: string
          description: Plot type (all, tco3_zm, vmro3_zm, tco3_return)
          default: "all"
          required: true
        - name: select
          in: query
          type: string
          description: Select models according to the {select} pattern
          required: false
      responses:
        200:
          description: "Successfully returned list of models"
          schema:
            $ref: '#/definitions/ListModels'
  /models/{model}:
    get:
      operationId: "o3api.api.get_model_detail"
      tags:
        - "models"
      summary: "Returning detailed information about a model"
      description: "Return detailed model info"
      produces:
        - "application/json"
      parameters:
        - name: model
          in: path
          type: string
          description: model name
          default: CCMI-1_ACCESS_ACCESS-CCM-refC2
          required: true
      responses:
        200:
          description: "Successfully returned model information"
          schema:
            $ref: '#/definitions/ModelInfo'
  /plots:
    get:
      operationId: "o3api.api.get_plot_types"
      tags:
        - "plots"
      summary: "Get the list of possible plots"
      description: "Get the list of possible plots"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successfully returned the list of possible plots"
          schema:
            $ref: '#/definitions/ListPlots'
  /plots/tco3_zm:
    post:
      operationId: "o3api.api.plot_tco3_zm"
      tags:
        - "plots"
      summary: "Create tco3_zm plot"
      description: "Create tco3_zm plot"
      produces:
        - "application/pdf"
        - "application/json"
      parameters:
        - $ref: '#/parameters/ModelParam'
        - $ref: '#/parameters/YearBeginParam'
        - $ref: '#/parameters/YearEndParam'
        - $ref: '#/parameters/MonthParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
      responses:
        200:
          description: "Successfully created a plot"
          schema:
            type: file
          schema:
            $ref: '#/definitions/TCO3Data'
#        default:
#          description: "Unexpected error"
#          schema:
#            $ref: "#/definitions/Error"
  /plots/tco3_return:
    post:
      operationId: "o3api.api.plot_tco3_return"
      tags:
        - "plots"
      summary: "Create tco3_return plot"
      description: "Create tco3_return plot"
      produces:
        - "application/pdf"
        - "application/json"
      parameters:
        - $ref: '#/parameters/ModelParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
        - name: ref_meas
          in: query
          type: string
          description: Reference observational measurument
          default: SBUV_GSFC_merged-SAT-ozone
          required: true
        - name: ref_year
          in: query
          type: integer
          description: Reference year for the obsevational measurement
          default: 1980
          required: true
      responses:
        200:
          description: "Successfully created a plot"
          schema:
            type: file
          schema:
            $ref: '#/definitions/TCO3ReturnData'
### comment /plots/vmro3_zm until we now how to produce plots # vkoz@210424
#  /plots/vmro3_zm:
#    post:
#      operationId: "o3api.api.vmro3_zm"
#      tags:
#        - "plots"
#      summary: "Create vmro3_zm plot"
#      description: "Create vmro3_zm plot"
#      produces:
#        - "application/pdf"
#        - "application/json"
#      parameters:
#        - $ref: '#/parameters/ModelParam'
#        - $ref: '#/parameters/YearBeginParam'
#        - $ref: '#/parameters/YearEndParam'
#      responses:
#        200:
#          description: "Successfully created a plot"
#          schema:
#            type: file
#          schema:
#            $ref: '#/definitions/VMRO3Data'
###
definitions:
  MetaInfo:
    type: object
    properties:
      author:
        type: string
      author-email:
        type: string
      home-page:
        type: string
      license:
        type: string
      name:
        type: string
      summary:
        type: string
      version:
        type: string
  ListData:
    type: array
    items:
      type: string
  Models:
    type: array
    items:        
      properties:
        model:
          type: string
        tco3_zm:
          type: object
        tco3_return:
          type: object
        vmro3_zm:
          type: object
  ListModels:
    type: array
    items:
      type: string
  ModelInfo:
    type: object
    properties:
      model:
        type: string
      tco3_zm:
        type: object
      tco3_return:
        type: object
      vmro3_zm:
        type: object
  ListPlots:
    type: array
    items:
      type: string
  TCO3Data:
    type: array
    items:        
      properties:
        model:
          type: string
        x:
          type: array
        y:
          type: array
  VMRO3Data:
    type: array
    items:        
      properties:
        model:
          type: string
        x:
          type: array
        y:
          type: array
  TCO3ReturnData:
    type: array
    items:        
      properties:
        model:
          type: string
        x:
          type: array
        y:
          type: array
  Error:
    type: string
