services:
  svcqc.dep_hazy-myrtle-capybara:
    image: grycap/im-client:ec3
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
    entrypoint: [/bin/sleep, infinity]
version: '3.7'
