services:
  svcqc.dep_hazy-myrtle-capybara:
    command: sleep 6000000
    image: grycap/im-client:ec3
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
