services:
  qc.sty_trippy-ultramarine-panda:
    command: sleep 6000000
    image: cytopia/pycodestyle
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
