services:
  o3api-testing:
    command: sleep 6000000
    image: indigodatacloud/ci-images:python3.6
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_crabby-jade-mongrel:
    command: sleep 6000000
    image: painless/tox
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_sleepy-buff-burmese:
    command: sleep 6000000
    image: painless/tox
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
